#!/bin/bash

mkdir -p ~/.jupyter/custom
cat _config/_static/custom.css >> ~/.jupyter/custom/custom.css
cat _config/_static/custom.js >> ~/.jupyter/custom/custom.js
cat _config/_static/custom.css >> $CONDA_PREFIX/lib/python3.7/site-packages/jupyterlab/themes/\@jupyterlab/theme-light-extension/index.css

mkdir -p ~/.ipython/profile_default/startup
cp _config/startup/* ~/.ipython/profile_default/startup/
rm -r _config

printenv > env.txt

