#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings


title                       : Case Studies in Neural Data Analysis  # The title of the book. Will be placed in the left navbar.
author                      : Mark Kramer and Uri Eden  # The author of the book
email                       : mak@math.bu.edu  # EDS2 (not sure if this does anything in sphinx)
# copyright                   : "2020"  # Copyright year to be placed in the footer
logo                        : "_config/logo/logo.png"  # A path to the book logo
exclude_patterns            : ["README.md", "LICENSE.md", "template.*", "ignore/*"]  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : "off" # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : ["README.md","LICENSE.md","ignore/*"]  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "_config/logo/favicon.ico"  # A path to a favicon image
  navbar_number_sections    : true # Add a number to each section in your left navbar
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
#   extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
#   extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : "G-54QV706BYJ"  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://mark-kramer.github.io/Case-Studies-Python"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebelab                  : true # Add a thebelab button to pages (requires the repository to run on Binder)

repository:
  url                       : https://github.com/Mark-Kramer/Case-Studies-Python/  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : "binder"  # Which branch of the repository should be used when creating links

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :   # A list of extra extensions to load by Sphinx.
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration
