#!/bin/bash

if [ -z "$NB_PYTHON_PREFIX" ] ; then NB_PYTHON_PREFIX=$CONDA_PREFIX ; fi
mkdir -p ~/.jupyter/custom
cat binder/custom.css >> ~/.jupyter/custom/custom.css
cat binder/custom.js >> ~/.jupyter/custom/custom.js
cat binder/custom.css >> $NB_PYTHON_PREFIX/share/jupyter/lab/themes/\@jupyterlab/theme-light-extension/index.css

mkdir -p ~/.ipython/profile_default/startup
cp binder/*CSNDA*.py ~/.ipython/profile_default/startup/
conda env create --file binder/temp.yml
conda activate case-studies

