#!/bin/bash

echo "CONDA_PREFIX: $CONDA_PREFIX" >> log.txt
echo "PWD: $PWD" >> log.txt
cat _config/_static/custom.css >> $CONDA_PREFIX/share/jupyter/lab/themes/\@jupyterlab/theme-light-extension/index.css

exec "$@"
